backend:
  name: github
  repo: CUPUM/site
  branch: main

publish_mode: editorial_workflow

media_folder: 'static/media'
public_folder: '/media'

i18n:
  structure: multiple_folders
  locales: [fr, en]
  default_locale: fr

collections:
  - name: projects
    label: Projects
    folder: 'projects'
    create: true
    i18n: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
